spiderpool:
    clusterDefaultPool:
      installIPv4IPPool: false
      installIPv6IPPool: false
      ipv4Gateway: 192.168.0.1
      ipv4IPPoolName: default-v4-ippool
      ipv4IPRanges:
        - 192.168.0.10-192.168.0.100
      ipv4Subnet: 192.168.0.0/16
      ipv4SubnetName: default-v4-subnet
      ipv6Gateway: fd00::1
      ipv6IPPoolName: default-v6-ippool
      ipv6IPRanges:
        - fd00::10-fd00::100
      ipv6Subnet: fd00::/112
      ipv6SubnetName: default-v6-subnet
    coordinator:
      detectGateway: true
      detectIPConflict: true
      enabled: true
      hijackCIDR:
        - 169.254.0.0/16
      mode: auto
      name: default
      podCIDRType: auto
      tunePodRoutes: true
    global:
      ciliumConfigMap: kube-system/cilium-config
      clusterDnsDomain: cluster.local
      cniBinHostPath: /opt/cni/bin
      cniConfHostPath: /etc/cni/net.d
      commonAnnotations: {}
      commonLabels: {}
      configName: spiderpool-conf
      imageRegistryOverride: 10.82.49.238
      ipamUNIXSocketHostPath: /var/run/spidernet/spiderpool.sock
      nameOverride: ''
    grafanaDashboard:
      annotations: {}
      install: false
      labels: {}
      namespace: ''
    ipam:
      enableIPv4: true
      enableIPv6: false
      enableKubevirtStaticIP: true
      enableSpiderSubnet: true
      enableStatefulSet: true
      gc:
        GcDeletingTimeOutPod:
          delay: 0
          enabled: true
        enabled: true
        gcAll:
          intervalInSecond: 600
      subnetDefaultFlexibleIPNumber: 1
    multus:
      enableMultusConfig: true
      multusCNI:
        defaultCniCRName: ''
        extraEnv: []
        extraVolumeMounts: []
        extraVolumes: []
        image:
          digest: ''
          imagePullSecrets: []
          pullPolicy: IfNotPresent
          registry: ghcr.m.daocloud.io
          repository: ghcr.m.daocloud.io/k8snetworkplumbingwg/multus-cni
          tag: v3.9.3
        install: true
        log:
          logFile: /var/log/multus.log
          logLevel: debug
        name: spiderpool-multus
        securityContext:
          privileged: true
        uninstall: true
    plugins:
      image:
        digest: ''
        imagePullSecrets: []
        pullPolicy: IfNotPresent
        registry: ghcr.m.daocloud.io
        repository: ghcr.m.daocloud.io/spidernet-io/spiderpool/spiderpool-plugins
        tag: v0.9.2
      installCNI: false
      installIpoibCNI: true
      installOvsCNI: true
      installRdmaCNI: true
      installibSriovCNI: true
    rdma:
      rdmaSharedDevicePlugin:
        deviceConfig:
          deviceIDs: '1017'
          periodicUpdateInterval: 300
          rdmaHcaMax: 500
          resourceName: hca_shared_devices
          resourcePrefix: spidernet.io
          vendors: 15b3
        image:
          digest: ''
          imagePullSecrets: []
          pullPolicy: IfNotPresent
          registry: ghcr.m.daocloud.io
          repository: ghcr.m.daocloud.io/mellanox/k8s-rdma-shared-dev-plugin
          tag: latest
        install: false
        name: spiderpool-rdma-shared-device-plugin
        podAnnotations: {}
        podLabels: {}
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 50Mi
        tolerations:
          - operator: Exists
        updateStrategy:
          rollingUpdate:
            maxUnavailable: 2
          type: RollingUpdate
    spiderpoolAgent:
      affinity: {}
      binName: /usr/bin/spiderpool-agent
      debug:
        gopsPort: 5712
        logLevel: info
      extraArgs: []
      extraEnv: []
      extraVolumeMounts: []
      extraVolumes: []
      healthChecking:
        livenessProbe:
          failureThreshold: 6
          periodSeconds: 10
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
        startupProbe:
          failureThreshold: 60
          periodSeconds: 2
      httpPort: 5710
      image:
        digest: ''
        imagePullSecrets: []
        pullPolicy: IfNotPresent
        registry: ghcr.m.daocloud.io
        repository: ghcr.m.daocloud.io/spidernet-io/spiderpool/spiderpool-agent
        tag: v0.9.0
      name: spiderpool-agent
      nodeSelector:
        kubernetes.io/os: linux
      podAnnotations: {}
      podLabels: {}
      priorityClassName: system-node-critical
      prometheus:
        enabled: false
        enabledDebugMetric: false
        port: 5711
        prometheusRule:
          annotations: {}
          enableWarningIPAMAllocationFailure: true
          enableWarningIPAMAllocationOverTime: true
          enableWarningIPAMHighAllocationDurations: true
          enableWarningIPAMReleaseFailure: true
          enableWarningIPAMReleaseOverTime: true
          install: false
          labels: {}
          namespace: ''
        serviceMonitor:
          annotations: {}
          install: false
          interval: 10s
          labels: {}
          namespace: ''
      resources:
        limits:
          cpu: 1000m
          memory: 1024Mi
        requests:
          cpu: 10m
          memory: 32Mi
      securityContext: {}
      service:
        annotations: {}
        type: ClusterIP
      serviceAccount:
        annotations: {}
        create: true
      tolerations:
        - operator: Exists
      updateStrategy:
        rollingUpdate:
          maxUnavailable: 2
        type: RollingUpdate
    spiderpoolController:
      affinity: {}
      binName: /usr/bin/spiderpool-controller
      debug:
        gopsPort: 5724
        logLevel: info
      extraArgs: []
      extraEnv: []
      extraVolumeMounts: []
      extraVolumes: []
      healthChecking:
        livenessProbe:
          failureThreshold: 6
          periodSeconds: 10
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
        startupProbe:
          failureThreshold: 30
          periodSeconds: 2
      hostnetwork: true
      httpPort: 5720
      image:
        digest: ''
        imagePullSecrets: []
        pullPolicy: IfNotPresent
        registry: ghcr.m.daocloud.io
        repository: ghcr.m.daocloud.io/spidernet-io/spiderpool/spiderpool-controller
        tag: v0.9.0
      name: spiderpool-controller
      nodeSelector:
        kubernetes.io/os: linux
      podAnnotations: {}
      podDisruptionBudget:
        enabled: false
        minAvailable: 1
      podLabels: {}
      priorityClassName: system-node-critical
      prometheus:
        enabled: false
        enabledDebugMetric: false
        port: 5721
        prometheusRule:
          annotations: {}
          enableWarningIPGCFailureCounts: true
          install: false
          labels: {}
          namespace: ''
        serviceMonitor:
          annotations: {}
          install: false
          interval: 10s
          labels: {}
          namespace: ''
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 10m
          memory: 64Mi
      securityContext: {}
      service:
        annotations: {}
        type: ClusterIP
      serviceAccount:
        annotations: {}
        create: true
      tls:
        auto:
          caExpiration: '73000'
          certExpiration: '73000'
          extraDnsNames: []
          extraIpAddresses: []
        certmanager:
          certValidityDuration: 365
          extraDnsNames: []
          extraIPAddresses: []
          issuerName: ''
        method: auto
        provided:
          tlsCa: ''
          tlsCert: ''
          tlsKey: ''
        secretName: spiderpool-controller-server-certs
      tolerations:
        - effect: NoSchedule
          operator: Exists
      webhookPort: 5722
    spiderpoolInit:
      affinity: {}
      binName: /usr/bin/spiderpool-init
      extraArgs: []
      extraEnv: []
      hostnetwork: true
      image:
        digest: ''
        imagePullSecrets: []
        pullPolicy: IfNotPresent
        registry: ghcr.m.daocloud.io
        repository: ghcr.m.daocloud.io/spidernet-io/spiderpool/spiderpool-controller
        tag: v0.9.0
      name: spiderpool-init
      nodeSelector:
        kubernetes.io/os: linux
      podAnnotations: {}
      podLabels: {}
      priorityClassName: system-node-critical
      readinessProbe:
        failureThreshold: 30
        periodSeconds: 10
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 32Mi
      securityContext: {}
      serviceAccount:
        annotations: {}
      tolerations:
        - operator: Exists
    sriov:
      affinity: {}
      enableAdmissionController: false
      hostnetwork: true
      image:
        ibSriovCni:
          repository: ghcr.m.daocloud.io/k8snetworkplumbingwg/ib-sriov-cni
          tag: v1.0.2
        imagePullSecrets: []
        operator:
          repository: ghcr.m.daocloud.io/k8snetworkplumbingwg/sriov-network-operator
          tag: v1.2.0
        pullPolicy: IfNotPresent
        registry: ghcr.io
        resourcesInjector:
          repository: ghcr.m.daocloud.io/k8snetworkplumbingwg/network-resources-injector
          tag: v1.5
        sriovCni:
          repository: ghcr.m.daocloud.io/k8snetworkplumbingwg/sriov-cni
          tag: v2.7.0
        sriovConfigDaemon:
          repository: >-
            ghcr.m.daocloud.io/k8snetworkplumbingwg/sriov-network-operator-config-daemon
          tag: v1.2.0
        sriovDevicePlugin:
          repository: ghcr.m.daocloud.io/k8snetworkplumbingwg/sriov-network-device-plugin
          tag: v3.5.1
        webhook:
          repository: ghcr.m.daocloud.io/k8snetworkplumbingwg/sriov-network-operator-webhook
          tag: v1.2.0
      install: false
      name: spiderpool-sriov-operator
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      replicas: 1
      resourcePrefix: spidernet.io
      resources:
        limits:
          cpu: 300m
          memory: 300Mi
        requests:
          cpu: 100m
          memory: 128Mi
      tolerations:
        - operator: Exists
  
